### ISSUE TITLE
buttonsActionHandler does not work

### ISSUE THREAD

**Issue by Swiftocrat** [nerzh/telegram-vapor-bot#1]
When I trying to use buttons callback as it showed in example, I'm facing problem when bot can't reply to user. It seems because bot somehow forgets chat id. Example does not work too, actually.

**Comment by nerzh** [comment]
Hello, I fixed example. 
Bot works normal, just on press button the update object does not have message

```swift
try update.message?.reply(text: update.callbackQuery?.data ?? "data not exist", bot: bot)
```

replace to

```swift
try update.callbackQuery?.message?.reply(text: update.callbackQuery?.data ?? "data not exist", bot: bot)
```

**Comment by Swiftocrat** [comment]
Thank you, I will try

**Comment by Swiftocrat** [comment]
Working

**Comment by nerzh** [comment]
> Thank you, I will try

Thanks you, too
