### ISSUE TITLE
Buttons in place of the keyboard

### ISSUE THREAD

**Issue by freefelt** [nerzh/telegram-vapor-bot#21]
Hi! Thank you for your work!
Please, show me tan example how to make buttons not in chat, but in place of the keyboard.
Is there any documentation?

**Comment by freefelt** [comment]
How to pass callback data to TGKeyboardButton?

**Comment by freefelt** [comment]
Apologize. It seemed to me that when I tried to make a bot on NodeJS, I could pass callback_data to KeyboardButton. Apparently, the buttons appeared, but I did not check the clicks on them, because then I used InlineKeyboard, and I tried KeyboardButton for the sake of interest.

**Comment by nerzh** [comment]
Hi, Keyboard buttons have no callback, you need to search by exact match of the button name
