### ISSUE TITLE
Thread 76: Fatal error: String index is out of bounds

### ISSUE THREAD

**Issue by evstarshov** [nerzh/telegram-vapor-bot#4]
Когда кто-то из пользователей пересылает в чат длинное сообщение, или перепост, бот падает с ошибкой Fatal error: String index is out of bounds со ссылкой на строку 70 в файле CommandHandler

![Снимок экрана 2022-01-12 в 12 04 08](https://user-images.githubusercontent.com/87355480/149097152-f206c87b-c61c-46c9-998b-5d8d15dbdc66.png)

**Comment by evstarshov** [comment]
Пример сообщения

<img width="1062" alt="Снимок экрана 2022-01-12 в 12 18 31" src="https://user-images.githubusercontent.com/87355480/149099323-bfe72fd3-77ee-46cf-878c-805c7942565d.png">

**Comment by nerzh** [comment]
а можешь тестовый код хендлера показать ?
мне надо повторить этот баг, спасибо

**Comment by evstarshov** [comment]
> а можешь тестовый код хендлера показать ?
> мне надо повторить этот баг, спасибо

Могу, но мне потом будет ужасно стыдно(

**Comment by evstarshov** [comment]
Я попробовал в строке 38 написать filters: TGFilter = !.forwarded, вроде бы пока не падает. Мне кажется баг возникает когда в чате кто-то репостит что-то

[Архив.zip](https://github.com/nerzh/telegram-vapor-bot/files/7871237/default.zip)
![Снимок экрана 2022-01-14 в 18 06 45](https://user-images.githubusercontent.com/87355480/149537735-c1da9913-4c6b-44a2-957f-2d6e6168d727.png)

**Comment by nerzh** [comment]
слушай, а есть ссылка на публичное сообщение из любого чата в телеграм, которое вызывает у тебя этот баг ?

**Comment by evstarshov** [comment]
> слушай, а есть ссылка на публичное сообщение из любого чата в телеграм, переслав которое вызывает у тебя этот баг ?

https://t.me/vkcomveloch/952063

**Comment by nerzh** [comment]
супер, поймал баг

**Comment by evstarshov** [comment]
Я как !.forwarded выставил, так с тех пор он не упал у меня. Хотя не ручаюсь что это лучшее решение.

**Comment by nerzh** [comment]
сделал, сейчас обновлю

**Comment by nerzh** [comment]
пробуй релиз 1.4.2
