### ISSUE TITLE
Request support for Concurrency and Web App.

### ISSUE THREAD

**Issue by JoneWang** [nerzh/telegram-vapor-bot#7]
Your project is a great library! It has a lot of fun features when combined with Vapor. The combination with Vapor is also great for making Telegram Web App for Bot.

Request support for these features:
* async/await makes it easier to read and is now supported by most of the libraries still being updated.
* Telegram is supporting Web App for Bot this year and we hope to add these features.
https://core.telegram.org/bots/webapps

**Comment by Butanediol** [comment]
So true! This project is really awesome.

BTW WebApp is already possible with this library. I have no experience in frontend development but I build a simple demo page with this framework.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/22426749/198920433-08a87aee-812c-4a59-a892-030dd6043ba3.png">

**Comment by nerzh** [comment]
@JoneWang support for async wait is already in the implementation, please wait a bit

**Comment by JoneWang** [comment]
> @JoneWang support for async wait is already in the implementation, please wait a bit

Thank you!

**Comment by griffenk** [comment]
w/o async await there is limited use.
